
-- ** tb_pix_enviados  **
-- DEVELOPED BY HVAR CONSULTING | DataOps team

truncate table `corporativo-poc-hvar.silver_bi.tb_pix_enviados`;

INSERT INTO `corporativo-poc-hvar.silver_bi.tb_pix_enviados` 
(            
      sk_pix_bloqueio_ordem_pagamento ,	
campo_livre ,	
canal_entrada ,	
chave_bloqueio ,	
chave_enderecamento ,	
cod_agencia ,	
cod_agencia_contra_parte ,	
cod_coligada ,	
cod_devolucao_pacs004 ,	
cod_ispb ,	
cod_ispb_contra_parte ,	
cod_operacao ,	
cod_usuario ,	
cpf_cnpj ,	
cpf_cnpj_contra_parte ,	
cpf_cnpj_iniciador ,	
data_hora_processamento_pix_enviado ,	
data_hora_registro_pix_enviado ,	
eh_agendado ,	
end_to_end_pix_enviado ,	
end_to_end_original ,	
finalidade_transacao ,	
id_bacen_psp_final ,	
id_bloqueio_ordem_pagamento ,	
id_devolucao ,	
id_idempotente_ebank ,	
id_ordem_pagamento_pix_enviado ,	
info_devolucao_pacs004 ,	
info_erros ,	
modalidade_agente ,	
modelo_ctb ,	
motivo_med ,	
nome ,	
nome_contra_parte ,	
nro_conta ,	
nro_conta_contra_parte ,	
nro_movimento ,	
origem_movimento ,	
prestador_servico_saque ,	
referencia_interna ,	
status_bloqueio ,	
tipo_conta ,	
tipo_conta_contra_parte ,	
uuid_bloqueio_devolucao_especial ,	
uuid_solicitacao_devolucao_especial ,	
valor ,	
valor_compra ,	
valor_saque ,	
valor_troco ,	
dataatualizacaoctrl_pix_enviado ,	
datainicioctrl_pix_enviado ,	
datainsercaoctrl_pix_enviado ,	
dataparticaoctrl_pix_enviado ,	
dt_carga_bronze_pix_enviado ,	
sk_pix_status_ordem_pagamento ,	
data_hora_processamento ,	
data_hora_registro ,	
id ,	
id_ordem_pagamento ,	
informacao_adicional ,	
status_ordem_pagamento ,	
dataatualizacaoctrl ,	
datafimctrl ,	
datainicioctrl ,	
datainsercaoctrl ,	
dataparticaoctrl ,	
dt_carga_bronze                                            
)
WITH bloqueio_ordem_pagamento AS (
  SELECT DISTINCT sk_pix_bloqueio_ordem_pagamento,
    campo_livre,
    canal_entrada,
    chave_bloqueio,
    chave_enderecamento,
    cod_agencia,
    cod_agencia_contra_parte,
    cod_coligada,
    cod_devolucao_pacs004,
    cod_ispb,
    cod_ispb_contra_parte,
    cod_operacao,
    cod_usuario,
    cpf_cnpj,
    cpf_cnpj_contra_parte,
    cpf_cnpj_iniciador,
    data_hora_processamento data_hora_processamento_pix_enviado,
    data_hora_registro data_hora_registro_pix_enviado,
    eh_agendado,
    end_to_end end_to_end_pix_enviado,
    end_to_end_original,
    finalidade_transacao,
    id_bacen_psp_final,
    id_bloqueio_ordem_pagamento,
    id_devolucao,
    id_idempotente_ebank,
    id_ordem_pagamento id_ordem_pagamento_pix_enviado,
    info_devolucao_pacs004,
    info_erros,
    modalidade_agente,
    modelo_ctb,
    motivo_med,
    nome,
    nome_contra_parte,
    nro_conta,
    nro_conta_contra_parte,
    nro_movimento,
    origem_movimento,
    prestador_servico_saque,
    referencia_interna,
    status_bloqueio,
    tipo_conta,
    tipo_conta_contra_parte,
    uuid_bloqueio_devolucao_especial,
    uuid_solicitacao_devolucao_especial,
    valor,
    valor_compra,
    valor_saque,
    valor_troco,
    dataatualizacaoctrl dataatualizacaoctrl_pix_enviado,
    datainicioctrl datainicioctrl_pix_enviado,
    datainsercaoctrl datainsercaoctrl_pix_enviado,
    dataparticaoctrl dataparticaoctrl_pix_enviado,
    dt_carga_bronze dt_carga_bronze_pix_enviado
  FROM
    `corporativo-poc-hvar.bronze_bi.bi_pix_tbl_pix_bloqueio_ordem_pagamento`
  WHERE
    TIMESTAMP_TRUNC(_PARTITIONTIME, DAY) = TIMESTAMP("2024-06-27") 
  ),
  status_ordem_pagamento AS(
  SELECT DISTINCT 
    sk_pix_status_ordem_pagamento,
    data_hora_processamento,
    data_hora_registro,
    id,
    id_ordem_pagamento,
    informacao_adicional,
    status_ordem_pagamento,
    dataatualizacaoctrl,
    datafimctrl,
    datainicioctrl,
    datainsercaoctrl,
    dataparticaoctrl,
    dt_carga_bronze
  FROM
    `corporativo-poc-hvar.bronze_bi.bi_pix_tbl_pix_status_ordem_pagamento`
  WHERE
    TIMESTAMP_TRUNC(_PARTITIONTIME, DAY) = TIMESTAMP("2024-06-27") 
    )

SELECT DISTINCT *
FROM        bloqueio_ordem_pagamento AS a
INNER JOIN  status_ordem_pagamento AS b
ON   a.id_ordem_pagamento_pix_enviado = b.id_ordem_pagamento