
-- **  tbl_info_banc_pessoas **
-- DEVELOPED BY kleber CONSULTING | DataOps team

 CREATE TABLE IF NOT EXISTS  `corporativo-poc.bronze_bi.bi_infobank_tbl_infobanc_pessoas`
(
    sk_infobanc_pessoas INT64,
  cgc_cpf STRING,
  sequencia STRING,
  nome STRING,
  nomefantasia STRING,
  tipopessoa STRING,
  indcgc_cpf STRING,
  status STRING,
  email STRING,
  datanascimento DATETIME,
  numdocumento STRING,
  tipodocumento STRING,
  orgaoexpedidor STRING,
  datadocumento DATETIME,
  codprofissao STRING,
  pai STRING,
  mae STRING,
  estcivil STRING,
  regcasamento STRING,
  conjuge STRING,
  sexo STRING,
  nacionalidade STRING,
  indfuncionario STRING,
  codsetor STRING,
  numregistro STRING,
  indcapitalaberto STRING,
  controleacionario STRING,
  capitalsocial NUMERIC,
  capitalaberto NUMERIC,
  indimportacao STRING,
  perimportacao NUMERIC,
  indexportacao STRING,
  perexportacao NUMERIC,
  numempregados INT64,
  ganho NUMERIC,
  dataatualizacao DATETIME,
  infofaturamento STRING,
  tipoinstituicao STRING,
  codbanco STRING,
  codselic STRING,
  codcetip STRING,
  nomeusuario STRING,
  uf STRING,
  situacaoatual STRING,
  regimetributacao STRING,
  origemcadastro STRING,
  codfuncao STRING,
  codcategoria STRING,
  codispb STRING,
  codpessoa STRING,
  codcontrole STRING,
  indtipidentcli STRING,
  datacadastro DATETIME,
  codnatureza STRING,
  indpermite_bc STRING,
  porte STRING,
  uf_municipio STRING,
  codmunicipio STRING,
  datavencimento DATETIME,
  paraisofiscal STRING,
  indautbank STRING,
  databalanco DATETIME,
  patrimonioliquido NUMERIC,
  entregue_cpf STRING,
  entregue_rg STRING,
  entregue_residencia STRING,
  entregue_ficha STRING,
  entregue_visita STRING,
  codpais STRING,
  renda_total NUMERIC,
  cpfconjuge STRING,
  sequenciaconjuge STRING,
  entregue_cartao STRING,
  entregue_proposta STRING,
  databalancete DATETIME,
  dataconsultabacen DATETIME,
  situacaobacen STRING,
  datafaturamento_de DATETIME,
  datafaturamento_ate DATETIME,
  exibir_relatorio_pendencias STRING,
  codcapitalsocial STRING,
  codnaturezaempresa STRING,
  escolaridade STRING,
  numdependentes INT64,
  codtipoempresa STRING,
  compras_ultimo_exercicio NUMERIC,
  vendas_ultimo_exercicio NUMERIC,
  nomefantasiaant STRING,
  dataatualizacaonomefantasia DATETIME,
  dataserasa DATETIME,
  endereco_eletronico STRING,
  ultima_alteracao_contratual DATETIME,
  indpermite_pcam STRING,
  codexterno STRING,
  titular STRING,
  menor_emancipado STRING,
  espolio STRING,
  codsegmento STRING,
  ano_inicio_atividade INT64,
  domiciliado_exterior STRING,
  codpais_domiciliado_exterior STRING,
  indpermite_fatca STRING,
  codfatca STRING,
  observacoes_fatca STRING,
  etnia STRING,
  situacaoreceita STRING,
  codcontrolereceita STRING,
  datasituacaoreceita DATETIME,
  arquivoreceita STRING,
  indpermite_email STRING,
  clientedigital STRING,
  codsetorcnae STRING,
  investidor_qualificado STRING,
  publico_alvo_fundo STRING,
  fundo_investidor_qualificado STRING,
  faturamento_passivo STRING,
  nao_participante_giin STRING,
  nome_patrocinadora STRING,
  cnpj_patrocinadora STRING,
  giin_patrocinadora STRING,
  subclassefatca STRING,
  digitoreceita STRING,
  nao_comunica_instituicao STRING,
  nao_documentada_crs STRING,
  codcrs STRING,
  dataentradaestrangeiro DATETIME,
  indbacenjud STRING,
  tipo_cli_exterior STRING,
  cod_cli_exterior STRING,
  cnpj_empresa_lider STRING,
  provincia_estrangeiro STRING,
  cidade_estrangeiro STRING,
  ativo_total NUMERIC,
  datainsercaoctrl DATETIME,
  datainicioctrl DATE,
  datafimctrl DATE,
  dataparticaoctrl DATE,
  dataatualizacaoctrl DATETIME,
  dt_carga_bronze DATETIME,

  PRIMARY KEY
    (cgc_cpf) NOT ENFORCED
)
PARTITION BY _PARTITIONDATE -- Replace by Client options sent

CLUSTER BY dataatualizacao
    

OPTIONS (
  DESCRIPTION = 'Table BI_INFOBANK_TBL_Infobanc_Pessoas clustered by dataatualizacao'
); 
