
-- ** dbo_clientes  **
-- DEVELOPED BY Kleber CONSULTING | DataOps team
truncate table `bronze_sqlserver_ab_infobanc.dbo_clientes`;

insert INTO  `bronze_sqlserver_ab_infobanc.dbo_clientes` 
(
codcliente,
  cgc_cpf,
  sequencia,
  nome,
  tipopessoa,
  codcategoria,
  tipotributacao,
  codatividade,
  codgerente,
  status,
  datacadastro,
  dataatualizacao,
  ind_factoring,
  clientehomebank,
  ind_tributacpmf,
  datavencimento,
  nomeusuario,
  numdocumento,
  tipodocumento,
  orgaoexpedidor,
  uf_orgaoexpedidor,
  datadocumento,
  regimetributacao,
  datarenovacao,
  origemcadastro,
  indinvestinstit,
  indisentoiof,
  codgerenteant,
  codfirma,
  codglobal,
  indautbank,
  codcoligada,
  codagencia,
  codccusto,
  codclassif_gerencial,
  mesclientedesde,
  anoclientedesde,
  obsclientedesde,
  datadesativacao,
  codarea,
  codsetor_atividade,
  cp_acc,
  cp_sec,
  intragrupo,
  dataatualizacaogerente,
  motivoalteracaogerente,
  codclassif_administrativa,
  clienteproblematico,
  codmotivoproblematico,
  codbasileia,
  id_ponto_atendimento,
  dt_carga_raw,
  dt_carga_bronze
)
    SELECT
      SAFE_CAST(codcliente AS STRING) AS codcliente,
      SAFE_CAST(cgc_cpf AS STRING) AS cgc_cpf,
      SAFE_CAST(sequencia AS STRING) AS sequencia,
      SAFE_CAST(nome AS STRING) AS nome,
      SAFE_CAST(tipopessoa AS STRING) AS tipopessoa,
      SAFE_CAST(codcategoria AS STRING) AS codcategoria,
      SAFE_CAST(tipotributacao AS STRING) AS tipotributacao,
      SAFE_CAST(codatividade AS STRING) AS codatividade,
      SAFE_CAST(codgerente AS STRING) AS codgerente,
      SAFE_CAST(status AS STRING) AS status,
      SAFE_CAST(datacadastro AS DATETIME) AS datacadastro,
      SAFE_CAST(dataatualizacao AS DATETIME) AS dataatualizacao,
      SAFE_CAST(ind_factoring AS STRING) AS ind_factoring,
      SAFE_CAST(clientehomebank AS STRING) AS clientehomebank,
      SAFE_CAST(ind_tributacpmf AS STRING) AS ind_tributacpmf,
      SAFE_CAST(datavencimento AS DATETIME) AS datavencimento,
      SAFE_CAST(nomeusuario AS STRING) AS nomeusuario,
      SAFE_CAST(numdocumento AS STRING) AS numdocumento,
      SAFE_CAST(tipodocumento AS STRING) AS tipodocumento,
      SAFE_CAST(orgaoexpedidor AS STRING) AS orgaoexpedidor,
      SAFE_CAST(uf_orgaoexpedidor AS STRING) AS uf_orgaoexpedidor,
      SAFE_CAST(datadocumento AS DATETIME) AS datadocumento,
      SAFE_CAST(regimetributacao AS STRING) AS regimetributacao,
      SAFE_CAST(datarenovacao AS DATETIME) AS datarenovacao,
      SAFE_CAST(origemcadastro AS STRING) AS origemcadastro,
      SAFE_CAST(indinvestinstit AS STRING) AS indinvestinstit,
      SAFE_CAST(indisentoiof AS STRING) AS indisentoiof,
      SAFE_CAST(codgerenteant AS STRING) AS codgerenteant,
      SAFE_CAST(codfirma AS STRING) AS codfirma,
      SAFE_CAST(codglobal AS STRING) AS codglobal,
      SAFE_CAST(indautbank AS STRING) AS indautbank,
      SAFE_CAST(codcoligada AS STRING) AS codcoligada,
      SAFE_CAST(codagencia AS STRING) AS codagencia,
      SAFE_CAST(codccusto AS STRING) AS codccusto,
      SAFE_CAST(codclassif_gerencial AS STRING) AS codclassif_gerencial,
      SAFE_CAST(mesclientedesde AS STRING) AS mesclientedesde,
      SAFE_CAST(anoclientedesde AS STRING) AS anoclientedesde,
      SAFE_CAST(obsclientedesde AS STRING) AS obsclientedesde,
      SAFE_CAST(datadesativacao AS DATETIME) AS datadesativacao,
      SAFE_CAST(codarea AS STRING) AS codarea,
      SAFE_CAST(codsetor_atividade AS STRING) AS codsetor_atividade,
      SAFE_CAST(cp_acc AS STRING) AS cp_acc,
      SAFE_CAST(cp_sec AS STRING) AS cp_sec,
      SAFE_CAST(intragrupo AS STRING) AS intragrupo,
      SAFE_CAST(dataatualizacaogerente AS DATETIME) AS dataatualizacaogerente,
      SAFE_CAST(motivoalteracaogerente AS STRING) AS motivoalteracaogerente,
      SAFE_CAST(codclassif_administrativa AS STRING) AS codclassif_administrativa,
      SAFE_CAST(clienteproblematico AS STRING) AS clienteproblematico,
      SAFE_CAST(codmotivoproblematico AS STRING) AS codmotivoproblematico,
      SAFE_CAST(codbasileia AS STRING) AS codbasileia,
      SAFE_CAST(id_ponto_atendimento AS NUMERIC) AS id_ponto_atendimento,
      SAFE_CAST(dt_carga_raw AS TIMESTAMP) AS dt_carga_raw,
      SAFE_CAST(CURRENT_DATETIME("-03:00") AS TIMESTAMP) AS dt_carga_bronze
        FROM
          `raw_sqlserver_ab_infobanc.dbo_clientes` 
          WHERE
      dt_carga_raw = (
        SELECT
          MAX(dt_carga_raw)
        FROM
          `raw_sqlserver_ab_infobanc.dbo_clientes`
      );
 
  