
-- ** tbl_conta_corrente_movto  **
-- DEVELOPED BY HVAR CONSULTING | DataOps team

MERGE INTO `corporativo-poc-hvar.bronze_bi.bi_contacorrente_tbl_contacorrentemovto` AS bronze
USING (
  SELECT
    * EXCEPT (rnk)
  FROM (
    SELECT DISTINCT
codcoligada		,	 
codagencia	    ,
nroconta	    ,
datamovto	    ,
nromovimento    ,
nrodocto	    ,
natureza	    ,
codposto	    ,
codgerente	    ,
sisorigem	    ,
datasist	    ,
codhist		    ,
valor		    ,
bcoorigem	    ,
ageorigem	    ,
sitcontabil	    ,
origem		    ,
status		    ,
estornado	    ,
dataestorno	    ,
nroarquivo	    ,
seqarquivo      ,
nroarqctb	    ,
codmodelo	    ,
tarifado	    ,
debitado	    ,
entradaage	    ,
nroorigem	    ,
valorcpmf	    ,
codtributacao	,
codisencao		,
dataexclusao	,
codusuario		,
dataatu			,
dtadebcpmf		,
agedestino		,
ctbinterage		,
nroestorno		,
chequesustado	,
nromovimentoeb	,
nsu_sgc			,
codbcoint		,
nrolote			,
datainsercaoctrl,
datainicioctrl	,
datafimctrl		,
dataparticaoctrl,
      
      ROW_NUMBER() OVER(PARTITION BY codagencia, nroconta, nromovimento ORDER BY datamovto DESC) AS rnk 
     
	 FROM
        `corporativo-poc-hvar.BI_RENDIMENTO.BI_CONTACORRENTE_TBL_ContaCorrenteMovto`
     --WHERE
        --DATE(_PARTITIONDATE) >= DATE_SUB(CURRENT_DATE(), INTERVAL 3 DAY)
    ) 
  WHERE
    rnk = 1
) AS raw

ON bronze.codagencia = raw.codagencia  
and bronze.nroconta = raw.nroconta  
and bronze.nromovimento = raw.nromovimento  

WHEN MATCHED THEN UPDATE SET
   bronze.codcoligada = raw.codcoligada,
  bronze.codagencia = raw.codagencia,
  bronze.nroconta = raw.nroconta,
  bronze.datamovto = raw.datamovto,
  bronze.nromovimento = raw.nromovimento,
  bronze.nrodocto = raw.nrodocto,
  bronze.natureza = raw.natureza,
  bronze.codposto = raw.codposto,
  bronze.codgerente = raw.codgerente,
  bronze.sisorigem = raw.sisorigem,
  bronze.datasist = raw.datasist,
  bronze.codhist = raw.codhist,
  bronze.valor = raw.valor,
  bronze.bcoorigem = raw.bcoorigem,
  bronze.ageorigem = raw.ageorigem,
  bronze.sitcontabil = raw.sitcontabil,
  bronze.origem = raw.origem,
  bronze.status = raw.status,
  bronze.estornado = raw.estornado,
  bronze.dataestorno = raw.dataestorno,
  bronze.nroarquivo = raw.nroarquivo,
  bronze.seqarquivo = raw.seqarquivo,
  bronze.nroarqctb = raw.nroarqctb,
  bronze.codmodelo = raw.codmodelo,
  bronze.tarifado = raw.tarifado,
  bronze.debitado = raw.debitado,
  bronze.entradaage = raw.entradaage,
  bronze.nroorigem = raw.nroorigem,
  bronze.valorcpmf = raw.valorcpmf,
  bronze.codtributacao = raw.codtributacao,
  bronze.codisencao = raw.codisencao,
  bronze.dataexclusao = raw.dataexclusao,
  bronze.codusuario = raw.codusuario,
  bronze.dataatu = raw.dataatu,
  bronze.dtadebcpmf = raw.dtadebcpmf,
  bronze.agedestino = raw.agedestino,
  bronze.ctbinterage = raw.ctbinterage,
  bronze.nroestorno = raw.nroestorno,
  bronze.chequesustado = raw.chequesustado,
  bronze.nromovimentoeb = raw.nromovimentoeb,
  bronze.nsu_sgc = raw.nsu_sgc,
  bronze.codbcoint = raw.codbcoint,
  bronze.nrolote = raw.nrolote,
  bronze.datainsercaoctrl = raw.datainsercaoctrl,
  bronze.datainicioctrl = raw.datainicioctrl,
  bronze.datafimctrl = raw.datafimctrl,
  bronze.dataparticaoctrl = raw.dataparticaoctrl	

WHEN NOT MATCHED THEN INSERT (
 codcoligada		,	
codagencia	    ,	
nroconta	    ,		
datamovto	    ,	
nromovimento    ,		
nrodocto	    ,		
natureza	    ,		
codposto	    ,		
codgerente	    ,	
sisorigem	    ,	
datasist	    ,		
codhist		    ,	
valor		    ,	
bcoorigem	    ,	
ageorigem	    ,	
sitcontabil	    ,	
origem		    ,	
status		    ,	
estornado	    ,	
dataestorno	    ,	
nroarquivo	    ,	
seqarquivo      ,		
nroarqctb	    ,	
codmodelo	    ,	
tarifado	    ,		
debitado	    ,		
entradaage	    ,	
nroorigem	    ,	
valorcpmf	    ,	
codtributacao	,	
codisencao		,	
dataexclusao	,		
codusuario		,	
dataatu			,	
dtadebcpmf		,	
agedestino		,	
ctbinterage		,	
nroestorno		,	
chequesustado	,	
nromovimentoeb	,	
nsu_sgc			,	
codbcoint		,	
nrolote			,	
datainsercaoctrl,		
datainicioctrl	,	
datafimctrl		,	
dataparticaoctrl,		
  dt_carga_bronze
)
VALUES (
raw.codcoligada			,	 
raw.codagencia	    	,
raw.nroconta	    			,
raw.datamovto	    			,
raw.nromovimento    			,
raw.nrodocto	    			,
raw.natureza	    			,
raw.codposto	    			,
raw.codgerente	    			,
raw.sisorigem	    			,
raw.datasist	    			,
raw.codhist		    			,
raw.valor		    			,
raw.bcoorigem	    			,
raw.ageorigem	    			,
raw.sitcontabil	    			,
raw.origem		    			,
raw.status		    			,
raw.estornado	    			,
raw.dataestorno	    			,
raw.nroarquivo	    			,
raw.seqarquivo      					,
raw.nroarqctb	    			,
raw.codmodelo	    			,
raw.tarifado	    					,
raw.debitado	    					,
raw.entradaage	    			,
raw.nroorigem	    			,
raw.valorcpmf	    			,
raw.codtributacao				,
raw.codisencao					,
raw.dataexclusao						,
raw.codusuario					,
raw.dataatu						,
raw.dtadebcpmf					,
raw.agedestino					,
raw.ctbinterage					,
raw.nroestorno					,
raw.chequesustado				,
raw.nromovimentoeb				,
raw.nsu_sgc						,
raw.codbcoint					,
raw.nrolote						,
raw.datainsercaoctrl					,
raw.datainicioctrl				,
raw.datafimctrl					,
raw.dataparticaoctrl					,
  CURRENT_DATETIME('-03:00')
);
