
-- ** bi_pix_mat_movimentacaodetalhe  **
-- DEVELOPED BY HVAR CONSULTING | DataOps team

MERGE INTO `corporativo-poc-hvar.bronze_bi.mat_movimentacaodetalhe` AS bronze
USING (
  SELECT
    * EXCEPT (rnk)
  FROM (
    SELECT DISTINCT
 idrow						,
anomes						,
data						,
horario						,
documento					,
nome						,
tipopessoa					,
tipobase					,
enviadosrecebidos			,
endtoend					,
datahoraregistro			,
codispborigem				,
codcoligadaorigem			,
codagenciaorigem			,
nrocontaorigem				,
tipocontaorigem				,
documentoorigem				,
nomeorigem					,
codispbdestino				,
codcoligadadestino			,
codagenciadestino			,
nrocontadestino				,
tipocontadestino			,
documentodestino			,
nomedestino					,
valor						,
origemmovimento				,
chaveenderecamento			,
canalentrada				,
coddevolucaopacs004			,
dataoperacaoretorno			,
motivorejeicao				,
usuariosistema				,
statusmensagem				,
diretoindireto				,
tipopessoaorigem			,
tipopessoadestino			,
mesmatitularidade			,
tipochave					,
participanteorigem			,
participantedestino			,
participante				,
codispb						,
desctipocontaorigem			,
desctipocontadestino		,
faixahorario				,
faixahorariofiltro			,
possuichave					,
transfinterna				,
devolucao					,
dtfaixahorario				,
sistema						,
codgerente					,
uuid_documento				,
iddocumento					,
clienteespecifico			,
relatoriocomerro			,
faixahorariolimites			,
tipomes						,
situacaobackoffice			,
campolivre					,
      
      ROW_NUMBER() OVER(PARTITION BY endtoend ORDER BY DataHoraRegistro DESC) AS rnk 
     
	 FROM
        `corporativo-poc-hvar.BI_RENDIMENTO.BI_PIX_MAT_MovimentacaoDetalhe`
     --WHERE
        --DATE(_PARTITIONDATE) >= DATE_SUB(CURRENT_DATE(), INTERVAL 3 DAY)
    ) 
  WHERE
    rnk = 1
) AS raw

ON bronze.endtoend = raw.endtoend  

WHEN MATCHED THEN UPDATE SET
 bronze.idrow					=		raw.idrow						,
bronze.anomes					=		raw.anomes						,
bronze.data						=	raw.data						,
bronze.horario					=		raw.horario						,
bronze.documento				=		raw.documento					,
bronze.nome						=	raw.nome						,
bronze.tipopessoa				=		raw.tipopessoa					,
bronze.tipobase					=	raw.tipobase					,
bronze.enviadosrecebidos		=		raw.enviadosrecebidos			,
bronze.endtoend					=	raw.endtoend					,
bronze.datahoraregistro			=	raw.datahoraregistro			,
bronze.codispborigem			=		raw.codispborigem				,
bronze.codcoligadaorigem		=		raw.codcoligadaorigem			,
bronze.codagenciaorigem			=	raw.codagenciaorigem			,
bronze.nrocontaorigem			=		raw.nrocontaorigem				,
bronze.tipocontaorigem			=		raw.tipocontaorigem				,
bronze.documentoorigem			=		raw.documentoorigem				,
bronze.nomeorigem				=		raw.nomeorigem					,
bronze.codispbdestino			=		raw.codispbdestino				,
bronze.codcoligadadestino		=		raw.codcoligadadestino			,
bronze.codagenciadestino		=		raw.codagenciadestino			,
bronze.nrocontadestino			=		raw.nrocontadestino				,
bronze.tipocontadestino			=	raw.tipocontadestino			,
bronze.documentodestino			=	raw.documentodestino			,
bronze.nomedestino				=		raw.nomedestino					,
bronze.valor					=		raw.valor						,
bronze.origemmovimento			=		raw.origemmovimento				,
bronze.chaveenderecamento		=		raw.chaveenderecamento			,
bronze.canalentrada				=	raw.canalentrada				,
bronze.coddevolucaopacs004		=		raw.coddevolucaopacs004			,
bronze.dataoperacaoretorno		=		raw.dataoperacaoretorno			,
bronze.motivorejeicao			=		raw.motivorejeicao				,
bronze.usuariosistema			=		raw.usuariosistema				,
bronze.statusmensagem			=		raw.statusmensagem				,
bronze.diretoindireto			=		raw.diretoindireto				,
bronze.tipopessoaorigem			=	raw.tipopessoaorigem			,
bronze.tipopessoadestino		=		raw.tipopessoadestino			,
bronze.mesmatitularidade		=		raw.mesmatitularidade			,
bronze.tipochave				=		raw.tipochave					,
bronze.participanteorigem		=		raw.participanteorigem			,
bronze.participantedestino		=		raw.participantedestino			,
bronze.participante				=	raw.participante				,
bronze.codispb					=		raw.codispb						,
bronze.desctipocontaorigem		=		raw.desctipocontaorigem			,
bronze.desctipocontadestino		=		raw.desctipocontadestino		,
bronze.faixahorario				=	raw.faixahorario				,
bronze.faixahorariofiltro		=		raw.faixahorariofiltro			,
bronze.possuichave				=		raw.possuichave					,
bronze.transfinterna			=		raw.transfinterna				,
bronze.devolucao				=		raw.devolucao					,
bronze.dtfaixahorario			=		raw.dtfaixahorario				,
bronze.sistema					=		raw.sistema						,
bronze.codgerente				=		raw.codgerente					,
bronze.uuid_documento			=		raw.uuid_documento				,
bronze.iddocumento				=		raw.iddocumento					,
bronze.clienteespecifico		=		raw.clienteespecifico			,
bronze.relatoriocomerro			=	raw.relatoriocomerro			,
bronze.faixahorariolimites		=		raw.faixahorariolimites			,
bronze.tipomes					=		raw.tipomes						,
bronze.situacaobackoffice		=		raw.situacaobackoffice			,
bronze.campolivre				=		raw.campolivre					
			

WHEN NOT MATCHED THEN INSERT (
idrow						,
anomes						,
data						,
horario						,
documento					,
nome						,
tipopessoa					,
tipobase					,
enviadosrecebidos			,
endtoend					,
datahoraregistro			,
codispborigem				,
codcoligadaorigem			,
codagenciaorigem			,
nrocontaorigem				,
tipocontaorigem				,
documentoorigem				,
nomeorigem					,
codispbdestino				,
codcoligadadestino			,
codagenciadestino			,
nrocontadestino				,
tipocontadestino			,
documentodestino			,
nomedestino					,
valor						,
origemmovimento				,
chaveenderecamento			,
canalentrada				,
coddevolucaopacs004			,
dataoperacaoretorno			,
motivorejeicao				,
usuariosistema				,
statusmensagem				,
diretoindireto				,
tipopessoaorigem			,
tipopessoadestino			,
mesmatitularidade			,
tipochave					,
participanteorigem			,
participantedestino			,
participante				,
codispb						,
desctipocontaorigem			,
desctipocontadestino		,
faixahorario				,
faixahorariofiltro			,
possuichave					,
transfinterna				,
devolucao					,
dtfaixahorario				,
sistema						,
codgerente					,
uuid_documento				,
iddocumento					,
clienteespecifico			,
relatoriocomerro			,
faixahorariolimites			,
tipomes						,
situacaobackoffice			,
campolivre					,
dt_carga_bronze 
)
VALUES (
raw.idrow						,
raw.anomes						,
raw.data						,
raw.horario						,
raw.documento					,
raw.nome						,
raw.tipopessoa					,
raw.tipobase					,
raw.enviadosrecebidos			,
raw.endtoend					,
raw.datahoraregistro			,
raw.codispborigem				,
raw.codcoligadaorigem			,
raw.codagenciaorigem			,
raw.nrocontaorigem				,
raw.tipocontaorigem				,
raw.documentoorigem				,
raw.nomeorigem					,
raw.codispbdestino				,
raw.codcoligadadestino			,
raw.codagenciadestino			,
raw.nrocontadestino				,
raw.tipocontadestino			,
raw.documentodestino			,
raw.nomedestino					,
raw.valor						,
raw.origemmovimento				,
raw.chaveenderecamento			,
raw.canalentrada				,
raw.coddevolucaopacs004			,
raw.dataoperacaoretorno			,
raw.motivorejeicao				,
raw.usuariosistema				,
raw.statusmensagem				,
raw.diretoindireto				,
raw.tipopessoaorigem			,
raw.tipopessoadestino			,
raw.mesmatitularidade			,
raw.tipochave					,
raw.participanteorigem			,
raw.participantedestino			,
raw.participante				,
raw.codispb						,
raw.desctipocontaorigem			,
raw.desctipocontadestino		,
raw.faixahorario				,
raw.faixahorariofiltro			,
raw.possuichave					,
raw.transfinterna				,
raw.devolucao					,
raw.dtfaixahorario				,
raw.sistema						,
raw.codgerente					,
raw.uuid_documento				,
raw.iddocumento					,
raw.clienteespecifico			,
raw.relatoriocomerro			,
raw.faixahorariolimites			,
raw.tipomes						,
raw.situacaobackoffice			,
raw.campolivre					,
CURRENT_DATETIME('-03:00')
);
