
-- ** tbl_conta_corrente_movto  **
-- DEVELOPED BY HVAR CONSULTING | DataOps team

MERGE INTO `corporativo-poc-hvar.bronze_bi.bi_infobank_tbl_infobanc_pessoas` AS bronze
USING (
  SELECT
    * EXCEPT (rnk)
  FROM (
    SELECT DISTINCT
sk_infobanc_pessoas	,
cgc_cpf				,
sequencia			,
nome				,
nomefantasia		,
tipopessoa			,
indcgc_cpf			,
status				,
email				,
datanascimento		,
numdocumento		,
tipodocumento		,
orgaoexpedidor		,
datadocumento		,
codprofissao		,
pai					,
mae					,
estcivil			,
regcasamento		,
conjuge				,
sexo				,
nacionalidade		,
indfuncionario		,
codsetor			,
numregistro			,
indcapitalaberto	,
controleacionario	,
capitalsocial		,
capitalaberto		,
indimportacao		,
perimportacao		,
indexportacao		,
perexportacao		,
numempregados		,
ganho				,
dataatualizacao		,
infofaturamento		,
tipoinstituicao		,
codbanco			,
codselic			,
codcetip			,
nomeusuario			,
uf					,
situacaoatual		,
regimetributacao	,
origemcadastro		,
codfuncao			,
codcategoria		,
codispb				,
codpessoa			,
codcontrole			,
indtipidentcli		,
datacadastro		,
codnatureza			,
indpermite_bc		,
porte				,
uf_municipio		,
codmunicipio		,
datavencimento		,
paraisofiscal		,
indautbank			,
databalanco			,
patrimonioliquido	,
entregue_cpf		,
entregue_rg			,
entregue_residencia	,
entregue_ficha		,
entregue_visita		,
codpais				,
renda_total			,
cpfconjuge			,
sequenciaconjuge	,
entregue_cartao		,
entregue_proposta	,
databalancete		,
dataconsultabacen	,
situacaobacen		,
datafaturamento_de	,
datafaturamento_ate  	,
exibir_relatorio_pendencias  ,
codcapitalsocial	,
codnaturezaempresa	,
escolaridade		,
numdependentes		,
codtipoempresa		,
compras_ultimo_exercicio 	,
vendas_ultimo_exercicio ,
nomefantasiaant	  	,
dataatualizacaonomefantasia  ,
dataserasa			,
endereco_eletronico  	,
ultima_alteracao_contratual  ,
indpermite_pcam	  	,
codexterno			,
titular			 	,
menor_emancipado	,
espolio			  	,
codsegmento		  	,
ano_inicio_atividade,
domiciliado_exterior,
codpais_domiciliado_exterior ,
indpermite_fatca	,
codfatca			,
observacoes_fatca	,
etnia				,
situacaoreceita	  	,
codcontrolereceita	,
datasituacaoreceita  	,
arquivoreceita		,
indpermite_email	,
clientedigital		,
codsetorcnae		,
investidor_qualificado,
publico_alvo_fundo	,
fundo_investidor_qualificado ,
faturamento_passivo 	,
nao_participante_giin,
nome_patrocinadora	,
cnpj_patrocinadora	,
giin_patrocinadora	,
subclassefatca		,
digitoreceita		,
nao_comunica_instituicao 	,
nao_documentada_crs  	,
codcrs				,
dataentradaestrangeiro,
indbacenjud			,
tipo_cli_exterior	,
cod_cli_exterior	,
cnpj_empresa_lider	,
provincia_estrangeiro,
cidade_estrangeiro	,
ativo_total			,
datainsercaoctrl	,
datainicioctrl		,
datafimctrl		  	,
dataparticaoctrl	,
dataatualizacaoctrl  , 
      ROW_NUMBER() OVER(PARTITION BY cgc_cpf ORDER BY dataatualizacao DESC) AS rnk 
     
	 FROM
        `corporativo-poc-hvar.BI_RENDIMENTO.BI_INFOBANK_TBL_Infobanc_Pessoas`
     --WHERE
        --DATE(_PARTITIONDATE) >= DATE_SUB(CURRENT_DATE(), INTERVAL 3 DAY)
    ) 
  WHERE
    rnk = 1
) AS raw

ON bronze.cgc_cpf = raw.cgc_cpf  

WHEN MATCHED THEN UPDATE SET
  bronze.sk_infobanc_pessoas = raw.sk_infobanc_pessoas,
  bronze.cgc_cpf = raw.cgc_cpf,
  bronze.sequencia = raw.sequencia,
  bronze.nome = raw.nome,
  bronze.nomefantasia = raw.nomefantasia,
  bronze.tipopessoa = raw.tipopessoa,
  bronze.indcgc_cpf = raw.indcgc_cpf,
  bronze.status = raw.status,
  bronze.email = raw.email,
  bronze.datanascimento = raw.datanascimento,
  bronze.numdocumento = raw.numdocumento,
  bronze.tipodocumento = raw.tipodocumento,
  bronze.orgaoexpedidor = raw.orgaoexpedidor,
  bronze.datadocumento = raw.datadocumento,
  bronze.codprofissao = raw.codprofissao,
  bronze.pai = raw.pai,
  bronze.mae = raw.mae,
  bronze.estcivil = raw.estcivil,
  bronze.regcasamento = raw.regcasamento,
  bronze.conjuge = raw.conjuge,
  bronze.sexo = raw.sexo,
  bronze.nacionalidade = raw.nacionalidade,
  bronze.indfuncionario = raw.indfuncionario,
  bronze.codsetor = raw.codsetor,
  bronze.numregistro = raw.numregistro,
  bronze.indcapitalaberto = raw.indcapitalaberto,
  bronze.controleacionario = raw.controleacionario,
  bronze.capitalsocial = raw.capitalsocial,
  bronze.capitalaberto = raw.capitalaberto,
  bronze.indimportacao = raw.indimportacao,
  bronze.perimportacao = raw.perimportacao,
  bronze.indexportacao = raw.indexportacao,
  bronze.perexportacao = raw.perexportacao,
  bronze.numempregados = raw.numempregados,
  bronze.ganho = raw.ganho,
  bronze.dataatualizacao = raw.dataatualizacao,
  bronze.infofaturamento = raw.infofaturamento,
  bronze.tipoinstituicao = raw.tipoinstituicao,
  bronze.codbanco = raw.codbanco,
  bronze.codselic = raw.codselic,
  bronze.codcetip = raw.codcetip,
  bronze.nomeusuario = raw.nomeusuario,
  bronze.uf = raw.uf,
  bronze.situacaoatual = raw.situacaoatual,
  bronze.regimetributacao = raw.regimetributacao,
  bronze.origemcadastro = raw.origemcadastro,
  bronze.codfuncao = raw.codfuncao,
  bronze.codcategoria = raw.codcategoria,
  bronze.codispb = raw.codispb,
  bronze.codpessoa = raw.codpessoa,
  bronze.codcontrole = raw.codcontrole,
  bronze.indtipidentcli = raw.indtipidentcli,
  bronze.datacadastro = raw.datacadastro,
  bronze.codnatureza = raw.codnatureza,
  bronze.indpermite_bc = raw.indpermite_bc,
  bronze.porte = raw.porte,
  bronze.uf_municipio = raw.uf_municipio,
  bronze.codmunicipio = raw.codmunicipio,
  bronze.datavencimento = raw.datavencimento,
  bronze.paraisofiscal = raw.paraisofiscal,
  bronze.indautbank = raw.indautbank,
  bronze.databalanco = raw.databalanco,
  bronze.patrimonioliquido = raw.patrimonioliquido,
  bronze.entregue_cpf = raw.entregue_cpf,
  bronze.entregue_rg = raw.entregue_rg,
  bronze.entregue_residencia = raw.entregue_residencia,
  bronze.entregue_ficha = raw.entregue_ficha,
  bronze.entregue_visita = raw.entregue_visita,
  bronze.codpais = raw.codpais,
  bronze.renda_total = raw.renda_total,
  bronze.cpfconjuge = raw.cpfconjuge,
  bronze.sequenciaconjuge = raw.sequenciaconjuge,
  bronze.entregue_cartao = raw.entregue_cartao,
  bronze.entregue_proposta = raw.entregue_proposta,
  bronze.databalancete = raw.databalancete,
  bronze.dataconsultabacen = raw.dataconsultabacen,
  bronze.situacaobacen = raw.situacaobacen,
  bronze.datafaturamento_de = raw.datafaturamento_de,
  bronze.datafaturamento_ate = raw.datafaturamento_ate,
  bronze.exibir_relatorio_pendencias = raw.exibir_relatorio_pendencias,
  bronze.codcapitalsocial = raw.codcapitalsocial,
  bronze.codnaturezaempresa = raw.codnaturezaempresa,
  bronze.escolaridade = raw.escolaridade,
  bronze.numdependentes = raw.numdependentes,
  bronze.codtipoempresa = raw.codtipoempresa,
  bronze.compras_ultimo_exercicio = raw.compras_ultimo_exercicio,
  bronze.vendas_ultimo_exercicio = raw.vendas_ultimo_exercicio,
  bronze.nomefantasiaant = raw.nomefantasiaant,
  bronze.dataatualizacaonomefantasia = raw.dataatualizacaonomefantasia,
  bronze.dataserasa = raw.dataserasa,
  bronze.endereco_eletronico = raw.endereco_eletronico,
  bronze.ultima_alteracao_contratual = raw.ultima_alteracao_contratual,
  bronze.indpermite_pcam = raw.indpermite_pcam,
  bronze.codexterno = raw.codexterno,
  bronze.titular = raw.titular,
  bronze.menor_emancipado = raw.menor_emancipado,
  bronze.espolio = raw.espolio,
  bronze.codsegmento = raw.codsegmento,
  bronze.ano_inicio_atividade = raw.ano_inicio_atividade,
  bronze.domiciliado_exterior = raw.domiciliado_exterior,
  bronze.codpais_domiciliado_exterior = raw.codpais_domiciliado_exterior,
  bronze.indpermite_fatca = raw.indpermite_fatca,
  bronze.codfatca = raw.codfatca,
  bronze.observacoes_fatca = raw.observacoes_fatca,
  bronze.etnia = raw.etnia,
  bronze.situacaoreceita = raw.situacaoreceita,
  bronze.codcontrolereceita = raw.codcontrolereceita,
  bronze.datasituacaoreceita = raw.datasituacaoreceita,
  bronze.arquivoreceita = raw.arquivoreceita,
  bronze.indpermite_email = raw.indpermite_email,
  bronze.clientedigital = raw.clientedigital,
  bronze.codsetorcnae = raw.codsetorcnae,
  bronze.investidor_qualificado = raw.investidor_qualificado,
  bronze.publico_alvo_fundo = raw.publico_alvo_fundo,
  bronze.fundo_investidor_qualificado = raw.fundo_investidor_qualificado,
  bronze.faturamento_passivo = raw.faturamento_passivo,
  bronze.nao_participante_giin = raw.nao_participante_giin,
  bronze.nome_patrocinadora = raw.nome_patrocinadora,
  bronze.cnpj_patrocinadora = raw.cnpj_patrocinadora,
  bronze.giin_patrocinadora = raw.giin_patrocinadora,
  bronze.subclassefatca = raw.subclassefatca,
  bronze.digitoreceita = raw.digitoreceita,
  bronze.nao_comunica_instituicao = raw.nao_comunica_instituicao,
  bronze.nao_documentada_crs = raw.nao_documentada_crs,
  bronze.codcrs = raw.codcrs,
  bronze.dataentradaestrangeiro = raw.dataentradaestrangeiro,
  bronze.indbacenjud = raw.indbacenjud,
  bronze.tipo_cli_exterior = raw.tipo_cli_exterior,
  bronze.cod_cli_exterior = raw.cod_cli_exterior,
  bronze.cnpj_empresa_lider = raw.cnpj_empresa_lider,
  bronze.provincia_estrangeiro = raw.provincia_estrangeiro,
  bronze.cidade_estrangeiro = raw.cidade_estrangeiro,
  bronze.ativo_total = raw.ativo_total,
  bronze.datainsercaoctrl = raw.datainsercaoctrl,
  bronze.datainicioctrl = raw.datainicioctrl,
  bronze.datafimctrl = raw.datafimctrl,
  bronze.dataparticaoctrl = raw.dataparticaoctrl,
  bronze.dataatualizacaoctrl = raw.dataatualizacaoctrl

WHEN NOT MATCHED THEN INSERT (
sk_infobanc_pessoas	,
cgc_cpf				,
sequencia			,
nome				,
nomefantasia		,
tipopessoa			,
indcgc_cpf			,
status				,
email				,
datanascimento		,
numdocumento		,
tipodocumento		,
orgaoexpedidor		,
datadocumento		,
codprofissao		,
pai					,
mae					,
estcivil			,
regcasamento		,
conjuge				,
sexo				,
nacionalidade		,
indfuncionario		,
codsetor			,
numregistro			,
indcapitalaberto	,
controleacionario	,
capitalsocial		,
capitalaberto		,
indimportacao		,
perimportacao		,
indexportacao		,
perexportacao		,
numempregados		,
ganho				,
dataatualizacao		,
infofaturamento		,
tipoinstituicao		,
codbanco			,
codselic			,
codcetip			,
nomeusuario			,
uf					,
situacaoatual		,
regimetributacao	,
origemcadastro		,
codfuncao			,
codcategoria		,
codispb				,
codpessoa			,
codcontrole			,
indtipidentcli		,
datacadastro		,
codnatureza			,
indpermite_bc		,
porte				,
uf_municipio		,
codmunicipio		,
datavencimento		,
paraisofiscal		,
indautbank			,
databalanco			,
patrimonioliquido	,
entregue_cpf		,
entregue_rg			,
entregue_residencia	,
entregue_ficha		,
entregue_visita		,
codpais				,
renda_total			,
cpfconjuge			,
sequenciaconjuge	,
entregue_cartao		,
entregue_proposta	,
databalancete		,
dataconsultabacen	,
situacaobacen		,
datafaturamento_de	,
datafaturamento_ate  	,
exibir_relatorio_pendencias  ,
codcapitalsocial	,
codnaturezaempresa	,
escolaridade		,
numdependentes		,
codtipoempresa		,
compras_ultimo_exercicio 	,
vendas_ultimo_exercicio ,
nomefantasiaant	  	,
dataatualizacaonomefantasia  ,
dataserasa			,
endereco_eletronico  	,
ultima_alteracao_contratual  ,
indpermite_pcam	  	,
codexterno			,
titular			 	,
menor_emancipado	,
espolio			  	,
codsegmento		  	,
ano_inicio_atividade,
domiciliado_exterior,
codpais_domiciliado_exterior ,
indpermite_fatca	,
codfatca			,
observacoes_fatca	,
etnia				,
situacaoreceita	  	,
codcontrolereceita	,
datasituacaoreceita  	,
arquivoreceita		,
indpermite_email	,
clientedigital		,
codsetorcnae		,
investidor_qualificado,
publico_alvo_fundo	,
fundo_investidor_qualificado ,
faturamento_passivo 	,
nao_participante_giin,
nome_patrocinadora	,
cnpj_patrocinadora	,
giin_patrocinadora	,
subclassefatca		,
digitoreceita		,
nao_comunica_instituicao 	,
nao_documentada_crs  	,
codcrs				,
dataentradaestrangeiro,
indbacenjud			,
tipo_cli_exterior	,
cod_cli_exterior	,
cnpj_empresa_lider	,
provincia_estrangeiro,
cidade_estrangeiro	,
ativo_total			,
datainsercaoctrl	,
datainicioctrl		,
datafimctrl		  	,
dataparticaoctrl	,
dataatualizacaoctrl  , 
  dt_carga_bronze
)
VALUES (
raw.sk_infobanc_pessoas	,
raw.cgc_cpf				,
raw.sequencia			,
raw.nome				,
raw.nomefantasia		,
raw.tipopessoa			,
raw.indcgc_cpf			,
raw.status				,
raw.email				,
raw.datanascimento		,
raw.numdocumento		,
raw.tipodocumento		,
raw.orgaoexpedidor		,
raw.datadocumento		,
raw.codprofissao		,
raw.pai					,
raw.mae					,
raw.estcivil			,
raw.regcasamento		,
raw.conjuge				,
raw.sexo				,
raw.nacionalidade		,
raw.indfuncionario		,
raw.codsetor			,
raw.numregistro			,
raw.indcapitalaberto	,
raw.controleacionario	,
raw.capitalsocial		,
raw.capitalaberto		,
raw.indimportacao		,
raw.perimportacao		,
raw.indexportacao		,
raw.perexportacao		,
raw.numempregados		,
raw.ganho				,
raw.dataatualizacao		,
raw.infofaturamento		,
raw.tipoinstituicao		,
raw.codbanco			,
raw.codselic			,
raw.codcetip			,
raw.nomeusuario			,
raw.uf					,
raw.situacaoatual		,
raw.regimetributacao	,
raw.origemcadastro		,
raw.codfuncao			,
raw.codcategoria		,
raw.codispb				,
raw.codpessoa			,
raw.codcontrole			,
raw.indtipidentcli		,
raw.datacadastro		,
raw.codnatureza			,
raw.indpermite_bc		,
raw.porte				,
raw.uf_municipio		,
raw.codmunicipio		,
raw.datavencimento		,
raw.paraisofiscal		,
raw.indautbank			,
raw.databalanco			,
raw.patrimonioliquido	,
raw.entregue_cpf		,
raw.entregue_rg			,
raw.entregue_residencia	,
raw.entregue_ficha		,
raw.entregue_visita		,
raw.codpais				,
raw.renda_total			,
raw.cpfconjuge			,
raw.sequenciaconjuge	,
raw.entregue_cartao		,
raw.entregue_proposta	,
raw.databalancete		,
raw.dataconsultabacen	,
raw.situacaobacen		,
raw.datafaturamento_de	,
raw.datafaturamento_ate  	,
raw.exibir_relatorio_pendencias  ,
raw.codcapitalsocial	,
raw.codnaturezaempresa	,
raw.escolaridade		,
raw.numdependentes		,
raw.codtipoempresa		,
raw.compras_ultimo_exercicio 	,
raw.vendas_ultimo_exercicio ,
raw.nomefantasiaant	  	,
raw.dataatualizacaonomefantasia  ,
raw.dataserasa			,
raw.endereco_eletronico  	,
raw.ultima_alteracao_contratual  ,
raw.indpermite_pcam	  	,
raw.codexterno			,
raw.titular			 	,
raw.menor_emancipado	,
raw.espolio			  	,
raw.codsegmento		  	,
raw.ano_inicio_atividade,
raw.domiciliado_exterior,
raw.codpais_domiciliado_exterior ,
raw.indpermite_fatca	,
raw.codfatca			,
raw.observacoes_fatca	,
raw.etnia				,
raw.situacaoreceita	  	,
raw.codcontrolereceita	,
raw.datasituacaoreceita  	,
raw.arquivoreceita		,
raw.indpermite_email	,
raw.clientedigital		,
raw.codsetorcnae		,
raw.investidor_qualificado,
raw.publico_alvo_fundo	,
raw.fundo_investidor_qualificado ,
raw.faturamento_passivo 	,
raw.nao_participante_giin,
raw.nome_patrocinadora	,
raw.cnpj_patrocinadora	,
raw.giin_patrocinadora	,
raw.subclassefatca		,
raw.digitoreceita		,
raw.nao_comunica_instituicao 	,
raw.nao_documentada_crs  	,
raw.codcrs				,
raw.dataentradaestrangeiro,
raw.indbacenjud			,
raw.tipo_cli_exterior	,
raw.cod_cli_exterior	,
raw.cnpj_empresa_lider	,
raw.provincia_estrangeiro,
raw.cidade_estrangeiro	,
raw.ativo_total			,
raw.datainsercaoctrl	,
raw.datainicioctrl		,
raw.datafimctrl		  	,
raw.dataparticaoctrl	,
raw.dataatualizacaoctrl  ,
  CURRENT_DATETIME('-03:00')
);
