
-- ** tbl_conta_corrente_conta  **
-- DEVELOPED BY HVAR CONSULTING | DataOps team

MERGE INTO `corporativo-poc-hvar.bronze_bi.bi_contacorrente_tbl_contacorrente_conta` AS bronze
USING (
  SELECT
    * EXCEPT (rnk)
  FROM (
    SELECT DISTINCT
codcoligada	,
codagencia	,
nroconta	,
dataatu	,
codposto	,
databertura	,
codgerente	,
especie	,
codsituacao		,
status	,
tipdepos	,
sdodia0	,
sdodia1	,
sdobloq0	,
sdobloq1	,	
modalori		,
dataultmov		,
dataultpro		,
dataultext		,
seqextrato		,
sdoextrato		,
perextrato		,
dataultdeb		,
extbloqueado	,
talbloqueado	,
tipotalao		,
qtdfltalao		,
estminimo		,
solautomat		,
nroultchq		,
codcoligmov		,
codagencmov		,
nrocontamov		,
ordemtransf		,
transfjuros		,
nromovimento	,
nropendente		,
nrofuturo		,
Codtributacao	,
codisencao		,
retencaocpmf	,
codagetroca		,
ultimosaldo		,
dataultsaldo	,
codusuario		,
provcpmfant		,
provcpmfatu		,
devcpmfant		,
devcpmfatu		,
nrodiasadpexc	,
nrodiasneg		,
cgc_cpfendereco	,
seqendereco		,
codendereco		,
envioextrato	,
homebanking		,
nrodiasmovhb	,
valorbloq		,
sitcredito		,
transfautoca	,
enviotalao		,
restricao		,
sequencial		,
ultimosaldobloq		,
      
      ROW_NUMBER() OVER(PARTITION BY codagencia, nroconta ORDER BY databertura DESC) AS rnk 
     
	 FROM
        `corporativo-poc-hvar.BI_RENDIMENTO.BI_CONTACORRENTE_TBL_ContaCorrente_Conta`
     --WHERE
        --DATE(_PARTITIONDATE) >= DATE_SUB(CURRENT_DATE(), INTERVAL 3 DAY)
    ) 
  WHERE
    rnk = 1
) AS raw

ON  bronze.codagencia	= raw.codagencia
and bronze.nroconta	= raw.nroconta

WHEN MATCHED THEN UPDATE SET
  bronze.codcoligada = raw.codcoligada,
  bronze.codagencia = raw.codagencia,
  bronze.nroconta = raw.nroconta,
  bronze.dataatu = raw.dataatu,
  bronze.codposto = raw.codposto,
  bronze.databertura = raw.databertura,
  bronze.codgerente = raw.codgerente,
  bronze.especie = raw.especie,
  bronze.codsituacao = raw.codsituacao,
  bronze.status = raw.status,
  bronze.tipdepos = raw.tipdepos,
  bronze.sdodia0 = raw.sdodia0,
  bronze.sdodia1 = raw.sdodia1,
  bronze.sdobloq0 = raw.sdobloq0,
  bronze.sdobloq1 = raw.sdobloq1,
  bronze.modalori = raw.modalori,
  bronze.dataultmov = raw.dataultmov,
  bronze.dataultpro = raw.dataultpro,
  bronze.dataultext = raw.dataultext,
  bronze.seqextrato = raw.seqextrato,
  bronze.sdoextrato = raw.sdoextrato,
  bronze.perextrato = raw.perextrato,
  bronze.dataultdeb = raw.dataultdeb,
  bronze.extbloqueado = raw.extbloqueado,
  bronze.talbloqueado = raw.talbloqueado,
  bronze.tipotalao = raw.tipotalao,
  bronze.qtdfltalao = raw.qtdfltalao,
  bronze.estminimo = raw.estminimo,
  bronze.solautomat = raw.solautomat,
  bronze.nroultchq = raw.nroultchq,
  bronze.codcoligmov = raw.codcoligmov,
  bronze.codagencmov = raw.codagencmov,
  bronze.nrocontamov = raw.nrocontamov,
  bronze.ordemtransf = raw.ordemtransf,
  bronze.transfjuros = raw.transfjuros,
  bronze.nromovimento = raw.nromovimento,
  bronze.nropendente = raw.nropendente,
  bronze.nrofuturo = raw.nrofuturo,
  bronze.Codtributacao = raw.Codtributacao,
  bronze.codisencao = raw.codisencao,
  bronze.retencaocpmf = raw.retencaocpmf,
  bronze.codagetroca = raw.codagetroca,
  bronze.ultimosaldo = raw.ultimosaldo,
  bronze.dataultsaldo = raw.dataultsaldo,
  bronze.codusuario = raw.codusuario,
  bronze.provcpmfant = raw.provcpmfant,
  bronze.provcpmfatu = raw.provcpmfatu,
  bronze.devcpmfant = raw.devcpmfant,
  bronze.devcpmfatu = raw.devcpmfatu,
  bronze.nrodiasadpexc = raw.nrodiasadpexc,
  bronze.nrodiasneg = raw.nrodiasneg,
  bronze.cgc_cpfendereco = raw.cgc_cpfendereco,
  bronze.seqendereco = raw.seqendereco,
  bronze.codendereco = raw.codendereco,
  bronze.envioextrato = raw.envioextrato,
  bronze.homebanking = raw.homebanking,
  bronze.nrodiasmovhb = raw.nrodiasmovhb,
  bronze.valorbloq = raw.valorbloq,
  bronze.sitcredito = raw.sitcredito,
  bronze.transfautoca = raw.transfautoca,
  bronze.enviotalao = raw.enviotalao,
  bronze.restricao = raw.restricao,
  bronze.sequencial = raw.sequencial,
  bronze.ultimosaldobloq = raw.ultimosaldobloq

WHEN NOT MATCHED THEN INSERT (
 codcoligada		,	
codagencia		,	
nroconta		,		
dataatu			,	
codposto		,		
databertura		,	
codgerente		,	
especie			,	
codsituacao		,	
status			,	
tipdepos		,		
sdodia0			,	
sdodia1			,	
sdobloq0		,		
sdobloq1		,				
modalori		,		
dataultmov		,	
dataultpro		,	
dataultext		,	
seqextrato		,	
sdoextrato		,	
perextrato		,	
dataultdeb		,	
extbloqueado	,		
talbloqueado	,		
tipotalao		,	
qtdfltalao		,	
estminimo		,	
solautomat		,	
nroultchq		,	
codcoligmov		,	
codagencmov		,	
nrocontamov		,	
ordemtransf		,	
transfjuros		,	
nromovimento	,		
nropendente		,	
nrofuturo		,	
Codtributacao	,	
codisencao		,	
retencaocpmf	,		
codagetroca		,	
ultimosaldo		,	
dataultsaldo	,		
codusuario		,	
provcpmfant		,	
provcpmfatu		,	
devcpmfant		,	
devcpmfatu		,	
nrodiasadpexc	,	
nrodiasneg		,	
cgc_cpfendereco	,	
seqendereco		,	
codendereco		,	
envioextrato	,		
homebanking		,	
nrodiasmovhb	,		
valorbloq		,	
sitcredito		,	
transfautoca	,		
enviotalao		,	
restricao		,	
sequencial		,	
ultimosaldobloq	,	
  dt_carga_bronze
)
VALUES (
 raw.codcoligada		,
raw.codagencia		,
raw.nroconta		,
raw.dataatu			,
raw.codposto		,
raw.databertura		,
raw.codgerente		,
raw.especie			,
raw.codsituacao		,
raw.status			,
raw.tipdepos		,
raw.sdodia0			,
raw.sdodia1			,
raw.sdobloq0		,
raw.sdobloq1		,
raw.modalori		,
raw.dataultmov		,
raw.dataultpro		,
raw.dataultext		,
raw.seqextrato		,
raw.sdoextrato		,
raw.perextrato		,
raw.dataultdeb		,
raw.extbloqueado	,
raw.talbloqueado	,
raw.tipotalao		,
raw.qtdfltalao		,
raw.estminimo		,
raw.solautomat		,
raw.nroultchq		,
raw.codcoligmov		,
raw.codagencmov		,
raw.nrocontamov		,
raw.ordemtransf		,
raw.transfjuros		,
raw.nromovimento	,
raw.nropendente		,
raw.nrofuturo		,
raw.Codtributacao	,
raw.codisencao		,
raw.retencaocpmf	,
raw.codagetroca		,
raw.ultimosaldo		,
raw.dataultsaldo	,
raw.codusuario		,
raw.provcpmfant		,
raw.provcpmfatu		,
raw.devcpmfant		,
raw.devcpmfatu		,
raw.nrodiasadpexc	,
raw.nrodiasneg		,
raw.cgc_cpfendereco	,
raw.seqendereco		,
raw.codendereco		,
raw.envioextrato	,
raw.homebanking		,
raw.nrodiasmovhb	,
raw.valorbloq		,
raw.sitcredito		,
raw.transfautoca	,
raw.enviotalao		,
raw.restricao		,
raw.sequencial		,
raw.ultimosaldobloq	 ,
  CURRENT_DATETIME('-03:00')
);
