
-- ** tbl_pix_bloqueio_ordem_pagamento  **
-- DEVELOPED BY HVAR CONSULTING | DataOps team

MERGE INTO `corporativo-poc-hvar.bronze_bi.bi_pix_tbl_pix_bloqueio_ordem_pagamento` AS bronze
USING (
  SELECT
    * EXCEPT (rnk)
  FROM (
    SELECT DISTINCT
  sk_pix_bloqueio_ordem_pagamento 	,
  campo_livre 						,
  canal_entrada 					,
  chave_bloqueio 					,
  chave_enderecamento 				,
  cod_agencia 						,
  cod_agencia_contra_parte 			,
  cod_coligada 						,
  cod_devolucao_pacs004 			,
  cod_ispb 							,
  cod_ispb_contra_parte 			,
  cod_operacao 						,
  cod_usuario 						,
  cpf_cnpj 							,
  cpf_cnpj_contra_parte 			,
  cpf_cnpj_iniciador 				,
  data_hora_processamento 			,
  data_hora_registro 				,
  eh_agendado 						,
  end_to_end 						,
  end_to_end_original 				,
  finalidade_transacao 				,
  id_bacen_psp_final 				,
  id_bloqueio_ordem_pagamento 		,
  id_devolucao 						,
  id_idempotente_ebank 				,
  id_ordem_pagamento 				,
  info_devolucao_pacs004 			,
  info_erros 						,
  modalidade_agente 				,
  modelo_ctb 						,
  motivo_med 						,
  nome 								,
  nome_contra_parte 				,
  nro_conta 						,
  nro_conta_contra_parte 			,
  nro_movimento 					,
  origem_movimento 					,
  prestador_servico_saque 			,
  referencia_interna 				,
  status_bloqueio 					,
  tipo_conta 						,
  tipo_conta_contra_parte 			,
  uuid_bloqueio_devolucao_especial 		,
  uuid_solicitacao_devolucao_especial ,
  valor 							,
  valor_compra 						,
  valor_saque 						,
  valor_troco 						,
  dataatualizacaoctrl 				,
  datafimctrl 						,
  datainicioctrl 					,
  datainsercaoctrl 					,
  dataparticaoctrl 					,
      
      ROW_NUMBER() OVER(PARTITION BY id_bloqueio_ordem_pagamento, data_hora_registro ORDER BY data_hora_registro DESC) AS rnk  
     
	 FROM
        `corporativo-poc-hvar.BI_RENDIMENTO.BI_PIX_TBL_Pix_Bloqueio_Ordem_Pagamento`
     --WHERE
        --DATE(_PARTITIONDATE) >= DATE_SUB(CURRENT_DATE(), INTERVAL 3 DAY)
    ) 
  WHERE
    rnk = 1
) AS raw

ON bronze.id_bloqueio_ordem_pagamento = raw.id_bloqueio_ordem_pagamento  
and bronze.data_hora_registro = raw.data_hora_registro  

WHEN MATCHED THEN UPDATE SET
  bronze.sk_pix_bloqueio_ordem_pagamento = raw.sk_pix_bloqueio_ordem_pagamento,
  bronze.campo_livre = raw.campo_livre,
  bronze.canal_entrada = raw.canal_entrada,
  bronze.chave_bloqueio = raw.chave_bloqueio,
  bronze.chave_enderecamento = raw.chave_enderecamento,
  bronze.cod_agencia = raw.cod_agencia,
  bronze.cod_agencia_contra_parte = raw.cod_agencia_contra_parte,
  bronze.cod_coligada = raw.cod_coligada,
  bronze.cod_devolucao_pacs004 = raw.cod_devolucao_pacs004,
  bronze.cod_ispb = raw.cod_ispb,
  bronze.cod_ispb_contra_parte = raw.cod_ispb_contra_parte,
  bronze.cod_operacao = raw.cod_operacao,
  bronze.cod_usuario = raw.cod_usuario,
  bronze.cpf_cnpj = raw.cpf_cnpj,
  bronze.cpf_cnpj_contra_parte = raw.cpf_cnpj_contra_parte,
  bronze.cpf_cnpj_iniciador = raw.cpf_cnpj_iniciador,
  bronze.data_hora_processamento = raw.data_hora_processamento,
  bronze.data_hora_registro = raw.data_hora_registro,
  bronze.eh_agendado = raw.eh_agendado,
  bronze.end_to_end = raw.end_to_end,
  bronze.end_to_end_original = raw.end_to_end_original,
  bronze.finalidade_transacao = raw.finalidade_transacao,
  bronze.id_bacen_psp_final = raw.id_bacen_psp_final,
  bronze.id_bloqueio_ordem_pagamento = raw.id_bloqueio_ordem_pagamento,
  bronze.id_devolucao = raw.id_devolucao,
  bronze.id_idempotente_ebank = raw.id_idempotente_ebank,
  bronze.id_ordem_pagamento = raw.id_ordem_pagamento,
  bronze.info_devolucao_pacs004 = raw.info_devolucao_pacs004,
  bronze.info_erros = raw.info_erros,
  bronze.modalidade_agente = raw.modalidade_agente,
  bronze.modelo_ctb = raw.modelo_ctb,
  bronze.motivo_med = raw.motivo_med,
  bronze.nome = raw.nome,
  bronze.nome_contra_parte = raw.nome_contra_parte,
  bronze.nro_conta = raw.nro_conta,
  bronze.nro_conta_contra_parte = raw.nro_conta_contra_parte,
  bronze.nro_movimento = raw.nro_movimento,
  bronze.origem_movimento = raw.origem_movimento,
  bronze.prestador_servico_saque = raw.prestador_servico_saque,
  bronze.referencia_interna = raw.referencia_interna,
  bronze.status_bloqueio = raw.status_bloqueio,
  bronze.tipo_conta = raw.tipo_conta,
  bronze.tipo_conta_contra_parte = raw.tipo_conta_contra_parte,
  bronze.uuid_bloqueio_devolucao_especial = raw.uuid_bloqueio_devolucao_especial,
  bronze.uuid_solicitacao_devolucao_especial = raw.uuid_solicitacao_devolucao_especial,
  bronze.valor = raw.valor,
  bronze.valor_compra = raw.valor_compra,
  bronze.valor_saque = raw.valor_saque,
  bronze.valor_troco = raw.valor_troco,
  bronze.dataatualizacaoctrl = raw.dataatualizacaoctrl,
  bronze.datafimctrl = raw.datafimctrl,
  bronze.datainicioctrl = raw.datainicioctrl,
  bronze.datainsercaoctrl = raw.datainsercaoctrl,
  bronze.dataparticaoctrl = raw.dataparticaoctrl

WHEN NOT MATCHED THEN INSERT (
 sk_pix_bloqueio_ordem_pagamento 	,
  campo_livre 						,
  canal_entrada 					,
  chave_bloqueio 					,
  chave_enderecamento 				,
  cod_agencia 						,
  cod_agencia_contra_parte 			,
  cod_coligada 						,
  cod_devolucao_pacs004 			,
  cod_ispb 							,
  cod_ispb_contra_parte 			,
  cod_operacao 						,
  cod_usuario 						,
  cpf_cnpj 							,
  cpf_cnpj_contra_parte 			,
  cpf_cnpj_iniciador 				,
  data_hora_processamento 			,
  data_hora_registro 				,
  eh_agendado 						,
  end_to_end 						,
  end_to_end_original 				,
  finalidade_transacao 				,
  id_bacen_psp_final 				,
  id_bloqueio_ordem_pagamento 		,
  id_devolucao 						,
  id_idempotente_ebank 				,
  id_ordem_pagamento 				,
  info_devolucao_pacs004 			,
  info_erros 						,
  modalidade_agente 				,
  modelo_ctb 						,
  motivo_med 						,
  nome 								,
  nome_contra_parte 				,
  nro_conta 						,
  nro_conta_contra_parte 			,
  nro_movimento 					,
  origem_movimento 					,
  prestador_servico_saque 			,
  referencia_interna 				,
  status_bloqueio 					,
  tipo_conta 						,
  tipo_conta_contra_parte 			,
  uuid_bloqueio_devolucao_especial 		,
  uuid_solicitacao_devolucao_especial ,
  valor 							,
  valor_compra 						,
  valor_saque 						,
  valor_troco 						,
  dataatualizacaoctrl 				,
  datafimctrl 						,
  datainicioctrl 					,
  datainsercaoctrl 					,
  dataparticaoctrl 					,
  dt_carga_bronze
)
VALUES (
  raw.sk_pix_bloqueio_ordem_pagamento 	,
  raw.campo_livre 						,
  raw.canal_entrada 					,
  raw.chave_bloqueio 					,
  raw.chave_enderecamento 				,
  raw.cod_agencia 						,
  raw.cod_agencia_contra_parte 			,
  raw.cod_coligada 						,
  raw.cod_devolucao_pacs004 			,
  raw.cod_ispb 							,
  raw.cod_ispb_contra_parte 			,
  raw.cod_operacao 						,
  raw.cod_usuario 						,
  raw.cpf_cnpj 							,
  raw.cpf_cnpj_contra_parte 			,
  raw.cpf_cnpj_iniciador 				,
  raw.data_hora_processamento 			,
  raw.data_hora_registro 				,
  raw.eh_agendado 						,
  raw.end_to_end 						,
  raw.end_to_end_original 				,
  raw.finalidade_transacao 				,
  raw.id_bacen_psp_final 				,
  raw.id_bloqueio_ordem_pagamento 		,
  raw.id_devolucao 						,
  raw.id_idempotente_ebank 				,
  raw.id_ordem_pagamento 				,
  raw.info_devolucao_pacs004 			,
  raw.info_erros 						,
  raw.modalidade_agente 				,
  raw.modelo_ctb 						,
  raw.motivo_med 						,
  raw.nome 								,
  raw.nome_contra_parte 				,
  raw.nro_conta 						,
  raw.nro_conta_contra_parte 			,
  raw.nro_movimento 					,
  raw.origem_movimento 					,
  raw.prestador_servico_saque 			,
  raw.referencia_interna 				,
  raw.status_bloqueio 					,
  raw.tipo_conta 						,
  raw.tipo_conta_contra_parte 			,
  raw.uuid_bloqueio_devolucao_especial 		,
  raw.uuid_solicitacao_devolucao_especial ,
  raw.valor 							,
  raw.valor_compra 						,
  raw.valor_saque 						,
  raw.valor_troco 						,
  raw.dataatualizacaoctrl 				,
  raw.datafimctrl 						,
  raw.datainicioctrl 					,
  raw.datainsercaoctrl 					,
  raw.dataparticaoctrl 					,
  CURRENT_DATETIME('-03:00')
);
