
-- ** tbl_info_banc_clientes  **
-- DEVELOPED BY HVAR CONSULTING | DataOps team

MERGE INTO `corporativo-poc-hvar.bronze_bi.bi_infobank_tbl_infobanc_clientes` AS bronze
USING (
  SELECT
    * EXCEPT (rnk)
  FROM (
    SELECT DISTINCT
codcliente		,
cgc_cpf			,
sequencia		,
nome			,
tipopessoa		,
codcategoria	,
tipotributacao	,
codatividade	,
codgerente		,
status			,
datacadastro	,
dataatualizacao	,
ind_factoring	,
clientehomebank	,
ind_tributacpmf	,
datavencimento	,
nomeusuario		,
numdocumento	,
tipodocumento	,
orgaoexpedidor	,
uf_orgaoexpedidor,
datadocumento	,
regimetributacao,
datarenovacao	,
origemcadastro	,
indinvestinstit	,
indisentoiof	,
codgerenteant	,
codfirma		,
codglobal		,
indautbank		,
codcoligada		,
codagencia		,
codccusto		,
codclassif_gerencial,
mesclientedesde	,
anoclientedesde	,
obsclientedesde	,
datadesativacao	,
codarea			,
codsetor_atividade,
cp_acc			,
cp_sec			,
intragrupo		,
dataatualizacaogerente,
motivoalteracaogerente,
codclassif_administrativa,
clienteproblematico	,
codmotivoproblematico,
cdc_cnpj_valido		,
dataparticaoctrl,	
      
      ROW_NUMBER() OVER(PARTITION BY cgc_cpf, codcliente ORDER BY datacadastro DESC) AS rnk 
     
	 FROM
        `corporativo-poc-hvar.BI_RENDIMENTO.BI_INFOBANK_TBL_InfoBanc_Clientes`
     --WHERE
        --DATE(_PARTITIONDATE) >= DATE_SUB(CURRENT_DATE(), INTERVAL 3 DAY)
    ) 
  WHERE
    rnk = 1
) AS raw

ON bronze.cgc_cpf = raw.cgc_cpf  
and bronze.codcliente = raw.codcliente  

WHEN MATCHED THEN UPDATE SET
  bronze.codcliente = raw.codcliente,
  bronze.cgc_cpf = raw.cgc_cpf,
  bronze.sequencia = raw.sequencia,
  bronze.nome = raw.nome,
  bronze.tipopessoa = raw.tipopessoa,
  bronze.codcategoria = raw.codcategoria,
  bronze.tipotributacao = raw.tipotributacao,
  bronze.codatividade = raw.codatividade,
  bronze.codgerente = raw.codgerente,
  bronze.status = raw.status,
  bronze.datacadastro = raw.datacadastro,
  bronze.dataatualizacao = raw.dataatualizacao,
  bronze.ind_factoring = raw.ind_factoring,
  bronze.clientehomebank = raw.clientehomebank,
  bronze.ind_tributacpmf = raw.ind_tributacpmf,
  bronze.datavencimento = raw.datavencimento,
  bronze.nomeusuario = raw.nomeusuario,
  bronze.numdocumento = raw.numdocumento,
  bronze.tipodocumento = raw.tipodocumento,
  bronze.orgaoexpedidor = raw.orgaoexpedidor,
  bronze.uf_orgaoexpedidor = raw.uf_orgaoexpedidor,
  bronze.datadocumento = raw.datadocumento,
  bronze.regimetributacao = raw.regimetributacao,
  bronze.datarenovacao = raw.datarenovacao,
  bronze.origemcadastro = raw.origemcadastro,
  bronze.indinvestinstit = raw.indinvestinstit,
  bronze.indisentoiof = raw.indisentoiof,
  bronze.codgerenteant = raw.codgerenteant,
  bronze.codfirma = raw.codfirma,
  bronze.codglobal = raw.codglobal,
  bronze.indautbank = raw.indautbank,
  bronze.codcoligada = raw.codcoligada,
  bronze.codagencia = raw.codagencia,
  bronze.codccusto = raw.codccusto,
  bronze.codclassif_gerencial = raw.codclassif_gerencial,
  bronze.mesclientedesde = raw.mesclientedesde,
  bronze.anoclientedesde = raw.anoclientedesde,
  bronze.obsclientedesde = raw.obsclientedesde,
  bronze.datadesativacao = raw.datadesativacao,
  bronze.codarea = raw.codarea,
  bronze.codsetor_atividade = raw.codsetor_atividade,
  bronze.cp_acc = raw.cp_acc,
  bronze.cp_sec = raw.cp_sec,
  bronze.intragrupo = raw.intragrupo,
  bronze.dataatualizacaogerente = raw.dataatualizacaogerente,
  bronze.motivoalteracaogerente = raw.motivoalteracaogerente,
  bronze.codclassif_administrativa = raw.codclassif_administrativa,
  bronze.clienteproblematico = raw.clienteproblematico,
  bronze.codmotivoproblematico = raw.codmotivoproblematico,
  bronze.cdc_cnpj_valido = raw.cdc_cnpj_valido,
  bronze.dataparticaoctrl = raw.dataparticaoctrl

WHEN NOT MATCHED THEN INSERT (
codcliente				,
cgc_cpf					,
sequencia				,
nome						,
tipopessoa				,
codcategoria				,
tipotributacao			,
codatividade				,
codgerente				,
status					,
datacadastro				,
dataatualizacao			,
ind_factoring			,
clientehomebank			,
ind_tributacpmf			,
datavencimento			,
nomeusuario				,
numdocumento				,
tipodocumento			,
orgaoexpedidor			,
uf_orgaoexpedidor		,
datadocumento			,
regimetributacao			,
datarenovacao			,
origemcadastro			,
indinvestinstit			,
indisentoiof				,
codgerenteant			,
codfirma					,
codglobal				,
indautbank				,
codcoligada				,
codagencia				,
codccusto				,
codclassif_gerencial		,
mesclientedesde			,
anoclientedesde			,
obsclientedesde			,
datadesativacao			,
codarea					,
codsetor_atividade		,
cp_acc					,
cp_sec					,
intragrupo				,
dataatualizacaogerente	,
motivoalteracaogerente	,
codclassif_administrativa,
clienteproblematico		,
codmotivoproblematico	,
cdc_cnpj_valido			,
dataparticaoctrl			,		
  dt_carga_bronze
)
VALUES (
raw.codcliente,
raw.cgc_cpf,
raw.sequencia,
raw.nome,
raw.tipopessoa							,
raw.codcategoria						,
raw.tipotributacao						,
raw.codatividade						,
raw.codgerente							,
raw.status,
raw.datacadastro						,
raw.dataatualizacao						,
raw.ind_factoring						,
raw.clientehomebank						,
raw.ind_tributacpmf						,
raw.datavencimento						,
raw.nomeusuario							,
raw.numdocumento						,
raw.tipodocumento						,
raw.orgaoexpedidor						,
raw.uf_orgaoexpedidor					,
raw.datadocumento						,
raw.regimetributacao					,
raw.datarenovacao						,
raw.origemcadastro						,
raw.indinvestinstit						,
raw.indisentoiof						,
raw.codgerenteant						,
raw.codfirma							,
raw.codglobal							,
raw.indautbank							,
raw.codcoligada							,
raw.codagencia							,
raw.codccusto							,
raw.codclassif_gerencial				,
raw.mesclientedesde						,
raw.anoclientedesde						,
raw.obsclientedesde						,
raw.datadesativacao						,
raw.codarea,
raw.codsetor_atividade					,
raw.cp_acc,
raw.cp_sec,
raw.intragrupo							,
raw.dataatualizacaogerente				,
raw.motivoalteracaogerente				,
raw.codclassif_administrativa,				
raw.clienteproblematico					,
raw.codmotivoproblematico				,
raw.cdc_cnpj_valido						,
raw.dataparticaoctrl						,
  CURRENT_DATETIME('-03:00')
);
