
-- ** tbl_pix_anotacao_credito  **
-- DEVELOPED BY HVAR CONSULTING | DataOps team

MERGE INTO `corporativo-poc-hvar.bronze_bi.bi_pix_tbl_pix_anotacaocredito` AS bronze
USING (
  SELECT
    * EXCEPT (rnk)
  FROM (
    SELECT DISTINCT
 sk_pix_anotacaocredito 		,
  data_hora_registro 			,
  data_hora_processamento 		,
  valor 						,
  id_idempotente_ebank 			,
  id_bacen_psp 					,
  nro_movimento 				,
  id_bacen_psp_final 			,
  id_anotacao_credito 			,
  end_to_end 					,
  cod_ispb 						,
  cod_coligada					,
  cod_agencia 					,
  nro_conta 					,
  tipo_conta 					,
  referencia_interna 			,
  chave_enderecamento 			,
  campo_livre 					,
  origem_movimento 				,
  cod_devolucao_pacs004 		,
  info_devolucao_pacs004 		,
  status_anotacao_credito 		,
  cod_usuario 					,
  info_erros 					,
  nome 							,
  nome_contra_parte 			,
  cod_operacao 					,
  cpf_cnpj 						,
  cod_ispb_contra_parte 		,
  cod_agencia_contra_parte 		,
  nro_conta_contra_parte 		,
  tipo_conta_contra_parte 		,
  cpf_cnpj_contra_parte 		,
  datainsercaoctrl 				,
  datainicioctrl 				,
  datafimctrl 					,
  dataparticaoctrl 				,
  dataatualizacaoctrl,		
      
      ROW_NUMBER() OVER(PARTITION BY id_anotacao_credito, data_hora_registro ORDER BY data_hora_registro DESC) AS rnk 
     
	 FROM
        `corporativo-poc-hvar.BI_RENDIMENTO.BI_PIX_TBL_Pix_AnotacaoCredito`
     --WHERE
        --DATE(_PARTITIONDATE) >= DATE_SUB(CURRENT_DATE(), INTERVAL 3 DAY)
    ) 
  WHERE
    rnk = 1
) AS raw

ON bronze.id_anotacao_credito = raw.id_anotacao_credito  
and bronze.data_hora_registro = raw.data_hora_registro 

WHEN MATCHED THEN UPDATE SET
   bronze.sk_pix_anotacaocredito = raw.sk_pix_anotacaocredito,
  bronze.data_hora_registro = raw.data_hora_registro,
  bronze.data_hora_processamento = raw.data_hora_processamento,
  bronze.valor = raw.valor,
  bronze.id_idempotente_ebank = raw.id_idempotente_ebank,
  bronze.id_bacen_psp = raw.id_bacen_psp,
  bronze.nro_movimento = raw.nro_movimento,
  bronze.id_bacen_psp_final = raw.id_bacen_psp_final,
  bronze.id_anotacao_credito = raw.id_anotacao_credito,
  bronze.end_to_end = raw.end_to_end,
  bronze.cod_ispb = raw.cod_ispb,
  bronze.cod_coligada = raw.cod_coligada,
  bronze.cod_agencia = raw.cod_agencia,
  bronze.nro_conta = raw.nro_conta,
  bronze.tipo_conta = raw.tipo_conta,
  bronze.referencia_interna = raw.referencia_interna,
  bronze.chave_enderecamento = raw.chave_enderecamento,
  bronze.campo_livre = raw.campo_livre,
  bronze.origem_movimento = raw.origem_movimento,
  bronze.cod_devolucao_pacs004 = raw.cod_devolucao_pacs004,
  bronze.info_devolucao_pacs004 = raw.info_devolucao_pacs004,
  bronze.status_anotacao_credito = raw.status_anotacao_credito,
  bronze.cod_usuario = raw.cod_usuario,
  bronze.info_erros = raw.info_erros,
  bronze.nome = raw.nome,
  bronze.nome_contra_parte = raw.nome_contra_parte,
  bronze.cod_operacao = raw.cod_operacao,
  bronze.cpf_cnpj = raw.cpf_cnpj,
  bronze.cod_ispb_contra_parte = raw.cod_ispb_contra_parte,
  bronze.cod_agencia_contra_parte = raw.cod_agencia_contra_parte,
  bronze.nro_conta_contra_parte = raw.nro_conta_contra_parte,
  bronze.tipo_conta_contra_parte = raw.tipo_conta_contra_parte,
  bronze.cpf_cnpj_contra_parte = raw.cpf_cnpj_contra_parte,
  bronze.datainsercaoctrl = raw.datainsercaoctrl,
  bronze.datainicioctrl = raw.datainicioctrl,
  bronze.datafimctrl = raw.datafimctrl,
  bronze.dataparticaoctrl = raw.dataparticaoctrl,
  bronze.dataatualizacaoctrl = raw.dataatualizacaoctrl			

WHEN NOT MATCHED THEN INSERT (
 sk_pix_anotacaocredito 		,
  data_hora_registro 			,
  data_hora_processamento 		,
  valor 						,
  id_idempotente_ebank 			,
  id_bacen_psp 					,
  nro_movimento 				,
  id_bacen_psp_final 			,
  id_anotacao_credito 			,
  end_to_end 					,
  cod_ispb 						,
  cod_coligada					,
  cod_agencia 					,
  nro_conta 					,
  tipo_conta 					,
  referencia_interna 			,
  chave_enderecamento 			,
  campo_livre 					,
  origem_movimento 				,
  cod_devolucao_pacs004 		,
  info_devolucao_pacs004 		,
  status_anotacao_credito 		,
  cod_usuario 					,
  info_erros 					,
  nome 							,
  nome_contra_parte 			,
  cod_operacao 					,
  cpf_cnpj 						,
  cod_ispb_contra_parte 		,
  cod_agencia_contra_parte 		,
  nro_conta_contra_parte 		,
  tipo_conta_contra_parte 		,
  cpf_cnpj_contra_parte 		,
  datainsercaoctrl 				,
  datainicioctrl 				,
  datafimctrl 					,
  dataparticaoctrl 				,
  dataatualizacaoctrl 			,
  dt_carga_bronze
)
VALUES (
raw.sk_pix_anotacaocredito 		,
raw.data_hora_registro 			,
raw.data_hora_processamento 		,
raw.valor 						,
raw.id_idempotente_ebank 			,
raw.id_bacen_psp 					,
raw.nro_movimento 				,
raw.id_bacen_psp_final 			,
raw.id_anotacao_credito 			,
raw.end_to_end 					,
raw.cod_ispb 						,
raw.cod_coligada					,
raw.cod_agencia 					,
raw.nro_conta 					,
raw.tipo_conta 					,
raw.referencia_interna 			,
raw.chave_enderecamento 			,
raw.campo_livre 					,
raw.origem_movimento 				,
raw.cod_devolucao_pacs004 		,
raw.info_devolucao_pacs004 		,
raw.status_anotacao_credito 		,
raw.cod_usuario 					,
raw.info_erros 					,
raw.nome 							,
raw.nome_contra_parte 			,
raw.cod_operacao 					,
raw.cpf_cnpj 						,
raw.cod_ispb_contra_parte 		,
raw.cod_agencia_contra_parte 		,
raw.nro_conta_contra_parte 		,
raw.tipo_conta_contra_parte 		,
raw.cpf_cnpj_contra_parte 		,
raw.datainsercaoctrl 				,
raw.datainicioctrl 				,
raw.datafimctrl 					,
raw.dataparticaoctrl 				,
raw.dataatualizacaoctrl 			,
  CURRENT_DATETIME('-03:00')
);
