
-- ** tbl_pix_movimentos_externos  **
-- DEVELOPED BY HVAR CONSULTING | DataOps team

MERGE INTO `corporativo-poc-hvar.bronze_bi.bi_pix_tbl_pix_movimentosexternos` AS bronze
USING (
  SELECT
    * EXCEPT (rnk)
  FROM (
    SELECT DISTINCT
 sk_pix_movimentosexternos  	,
  data_hora_registro 			,
  data_hora_processamento 		,
  valor 						,
  id_idempotente_ebank 			,
  id 							,
  id_ordem_pagamento 			,
  nro_movimento 				,
  id_bacen_psp_final 			,
  id_bloqueio_ordem_pagamento 	,
  id_msg 						,
  cod_msg 						,
  mensagem 						,
  cod_usuario 					,
  status_ordem_pagamento 		,
  informacao_adicional 			,
  info_devolucao_pacs004 		,
  canal_entrada 				,
  id_devolucao 					,
  cod_operacao 					,
  campo_livre 					,
  origem_movimento 				,
  chave_enderecamento 			,
  referencia_interna 			,
  cod_devolucao_pacs004 		,
  tipo_conta_contra_parte 		,
  cpf_cnpj_contra_parte 		,
  status_bloqueio 				,
  info_erros 					,
  nome_contra_parte 			,
  nome 							,
  nro_conta 					,
  tipo_conta 					,
  cpf_cnpj 						,
  cod_ispb_contra_parte 		,
  cod_agencia_contra_parte 		,
  nro_conta_contra_parte 		,
  id_idempotente 				,
  end_to_end 					,
  chave_bloqueio 				,
  cod_ispb 						,
  cod_coligada 					,
  cod_agencia 					,
  datainsercaoctrl 				,
  datainicioctrl 				,
  datafimctrl 					,
  dataparticaoctrl				,
  dataatualizacaoctrl 			,
      
      ROW_NUMBER() OVER(PARTITION BY end_to_end,cod_ispb ORDER BY data_hora_processamento DESC) AS rnk 
     
	 FROM
        `corporativo-poc-hvar.BI_RENDIMENTO.BI_PIX_TBL_Pix_MovimentosExternos`
     --WHERE
        --DATE(_PARTITIONDATE) >= DATE_SUB(CURRENT_DATE(), INTERVAL 3 DAY)
    ) 
  WHERE
    rnk = 1
) AS raw

ON bronze.end_to_end = raw.end_to_end  
and  bronze.cod_ispb = raw.cod_ispb  

WHEN MATCHED THEN UPDATE SET
 bronze.sk_pix_movimentosexternos               = raw.sk_pix_movimentosexternos  	,
bronze.data_hora_registro 			                = raw.data_hora_registro 			,
bronze.data_hora_processamento 	                = raw.data_hora_processamento 		,
bronze.valor 						                        = raw.valor 						,
bronze.id_idempotente_ebank 		                = raw.id_idempotente_ebank 			,
bronze.id 							                        = raw.id 							,
bronze.id_ordem_pagamento 			                = raw.id_ordem_pagamento 			,
bronze.nro_movimento 				                    = raw.nro_movimento 				,
bronze.id_bacen_psp_final 			                = raw.id_bacen_psp_final 			,
bronze.id_bloqueio_ordem_pagamento              = raw.id_bloqueio_ordem_pagamento 	,
bronze.id_msg 						                      = raw.id_msg 						,
bronze.cod_msg 					                        = raw.cod_msg 						,
bronze.mensagem 					                      = raw.mensagem 						,
bronze.cod_usuario 				                      = raw.cod_usuario 					,
bronze.status_ordem_pagamento 		              = raw.status_ordem_pagamento 		,
bronze.informacao_adicional 	                	= raw.informacao_adicional 			,
bronze.info_devolucao_pacs004 		              = raw.info_devolucao_pacs004 		,
bronze.canal_entrada 			  	                  = raw.canal_entrada 				,
bronze.id_devolucao 				                    = raw.id_devolucao 					,
bronze.cod_operacao 				                    = raw.cod_operacao 					,
bronze.campo_livre 				                      = raw.campo_livre 					,
bronze.origem_movimento 			                  = raw.origem_movimento 				,
bronze.chave_enderecamento 		                  = raw.chave_enderecamento 			,
bronze.referencia_interna 			                = raw.referencia_interna 			,
bronze.cod_devolucao_pacs004 		                = raw.cod_devolucao_pacs004 		,
bronze.tipo_conta_contra_parte 	                = raw.tipo_conta_contra_parte 		,
bronze.cpf_cnpj_contra_parte 		                = raw.cpf_cnpj_contra_parte 		,
bronze.status_bloqueio 			                    = raw.status_bloqueio 				,
bronze.info_erros 					                    = raw.info_erros 					,
bronze.nome_contra_parte 			                  = raw.nome_contra_parte 			,
bronze.nome 						                        = raw.nome 							,
bronze.nro_conta 					                      = raw.nro_conta 					,
bronze.tipo_conta 					                    = raw.tipo_conta 					,
bronze.cpf_cnpj 					                      = raw.cpf_cnpj 						,
bronze.cod_ispb_contra_parte 		                = raw.cod_ispb_contra_parte 		,
bronze.cod_agencia_contra_parte                 = raw.cod_agencia_contra_parte 		,
bronze.nro_conta_contra_parte 		              = raw.nro_conta_contra_parte 		,
bronze.id_idempotente 				                  = raw.id_idempotente 				,
bronze.end_to_end 					                    = raw.end_to_end 					,
bronze.chave_bloqueio 				                  = raw.chave_bloqueio 				,
bronze.cod_ispb 					                      = raw.cod_ispb 						,
bronze.cod_coligada 				                    = raw.cod_coligada 					,
bronze.cod_agencia 				                      = raw.cod_agencia 					,
bronze.datainsercaoctrl 			                  = raw.datainsercaoctrl 				,
bronze.datainicioctrl 			  	                = raw.datainicioctrl 				,
bronze.datafimctrl 				                      = raw.datafimctrl 					,
bronze.dataparticaoctrl			                    = raw.dataparticaoctrl				,
bronze.dataatualizacaoctrl 		                  = raw.dataatualizacaoctrl 		

WHEN NOT MATCHED THEN INSERT (
 sk_pix_movimentosexternos  	,
  data_hora_registro 			,
  data_hora_processamento 		,
  valor 						,
  id_idempotente_ebank 			,
  id 							,
  id_ordem_pagamento 			,
  nro_movimento 				,
  id_bacen_psp_final 			,
  id_bloqueio_ordem_pagamento 	,
  id_msg 						,
  cod_msg 						,
  mensagem 						,
  cod_usuario 					,
  status_ordem_pagamento 		,
  informacao_adicional 			,
  info_devolucao_pacs004 		,
  canal_entrada 				,
  id_devolucao 					,
  cod_operacao 					,
  campo_livre 					,
  origem_movimento 				,
  chave_enderecamento 			,
  referencia_interna 			,
  cod_devolucao_pacs004 		,
  tipo_conta_contra_parte 		,
  cpf_cnpj_contra_parte 		,
  status_bloqueio 				,
  info_erros 					,
  nome_contra_parte 			,
  nome 							,
  nro_conta 					,
  tipo_conta 					,
  cpf_cnpj 						,
  cod_ispb_contra_parte 		,
  cod_agencia_contra_parte 		,
  nro_conta_contra_parte 		,
  id_idempotente 				,
  end_to_end 					,
  chave_bloqueio 				,
  cod_ispb 						,
  cod_coligada 					,
  cod_agencia 					,
  datainsercaoctrl 				,
  datainicioctrl 				,
  datafimctrl 					,
  dataparticaoctrl				,
  dataatualizacaoctrl 			,
  dt_carga_bronze
)
VALUES (
    raw.sk_pix_movimentosexternos,
  raw.data_hora_registro,
  raw.data_hora_processamento 		,
  raw.valor 						,
  raw.id_idempotente_ebank 			,
  raw.id,
  raw.id_ordem_pagamento 			,
  raw.nro_movimento 				,
  raw.id_bacen_psp_final 			,
  raw.id_bloqueio_ordem_pagamento 	,
  raw.id_msg 						,
  raw.cod_msg 						,
  raw.mensagem 						,
  raw.cod_usuario 					,
  raw.status_ordem_pagamento 		,
  raw.informacao_adicional 			,
  raw.info_devolucao_pacs004 		,
  raw.canal_entrada 				,
  raw.id_devolucao 					,
  raw.cod_operacao 					,
  raw.campo_livre 					,
  raw.origem_movimento 				,
  raw.chave_enderecamento 			,
  raw.referencia_interna 			,
  raw.cod_devolucao_pacs004 		,
  raw.tipo_conta_contra_parte 		,
  raw.cpf_cnpj_contra_parte 		,
  raw.status_bloqueio 				,
  raw.info_erros 					,
  raw.nome_contra_parte 			,
  raw.nome 							,
  raw.nro_conta 					,
  raw.tipo_conta 					,
  raw.cpf_cnpj 						,
  raw.cod_ispb_contra_parte 		,
  raw.cod_agencia_contra_parte 		,
  raw.nro_conta_contra_parte 		,
  raw.id_idempotente 				,
  raw.end_to_end 					,
  raw.chave_bloqueio 				,
  raw.cod_ispb 						,
  raw.cod_coligada 					,
  raw.cod_agencia 					,
  raw.datainsercaoctrl 				,
  raw.datainicioctrl 				,
  raw.datafimctrl 					,
  raw.dataparticaoctrl				,
  raw.dataatualizacaoctrl 			,
  CURRENT_DATETIME('-03:00')
);
